//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookreview
    {
        public int id { get; set; }
        public Nullable<int> bookid { get; set; }
        public Nullable<int> userid { get; set; }
        public string userreview { get; set; }
        public Nullable<System.DateTime> reviewdate { get; set; }
    }
}
