//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditTrail> AuditTrail { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Bookrating> Bookrating { get; set; }
        public virtual DbSet<Bookreview> Bookreview { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BooksOrder> BooksOrder { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<userroles> userroles { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
